### ISSUE TITLE
How to use the model generated by this plug-in to make predictions,

### ISSUE THREAD

**Issue by pacelu** [azavea/raster-vision-fastai-plugin#24]
![image](https://user-images.githubusercontent.com/12770958/60557145-e37f8e00-9d76-11e9-848d-0bf5d70a356c.png)
rastervison   predict  package  input.tif  output.tif?
This command does not predict success

**Comment by pacelu** [comment]
Solutions:
Enter the plug-in directory and execute the command:
cd raster-vision-fastai-plugin
rastervision -p fastai predict  predict_package   input.tif output.tif

**Comment by lewfish** [comment]
Yup, you have to specify the profile to the command.
