### ISSUE TITLE
Possible pytorch / fastAI version mismatch: AttributeError: module 'torch' has no attribute 'gesv'

### ISSUE THREAD

**Issue by Rabscuttler** [azavea/raster-vision-fastai-plugin#27]
I got an error running with latest Docker image ([full stacktrace](https://pastebin.com/53BgteGS)):

`File "/opt/conda/lib/python3.6/site-packages/fastai/vision/transform.py", line 233, in <module>
    _solve_func = getattr(torch, 'solve', torch.gesv)`

`AttributeError: module 'torch' has no attribute 'gesv'`

FastAI forums report pytorch / Fastai version issues (e.g see [here](https://forums.fast.ai/t/fastai-pytorch-import-error/52201)). 

Changing fastai version to 1.0.57 in the docker file, ie 
`ARG FASTAI_COMMIT=585d107709c9af8d88ddf2e20eb06b4ad7f4f70f`
->
`ARG FASTAI_COMMIT=1.0.57`
worked for me.

**Comment by Manojkl** [comment]
The new version of torch does not support gesv and uses the solve function.

```
Kt, _ = torch.gesv(P.mm(H.t()).t(), S)
Kt, _ = torch.solve(P.mm(H.t()).t(), S)
```
